[project]
name = "demo"
version = "0.1.0"
description = "Demo project for Interface"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.0",
    "flask-cors>=5.0.0",
    "openai>=1.61.1",
    "pytest>=8.3.4",
    "rich>=13.9.4",
    "ruff>=0.9.6",
]
